name: Deploy Vite React App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Update to v3 for Node.js 20 support

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Update to v3 for Node.js 20 support
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --verbose

      - name: Build the project
        run: npm run build --verbose

      - name: Deploy to Hostinger
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp
          lftp -e "mirror -R dist/ public_html/; bye" -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ftp://82.180.168.32
